
# This is the server logic for a Shiny web application.
# You can find out more about building applications with Shiny here:
# 
# http://www.rstudio.com/shiny/
#

library(shiny)
library(ggplot2)
library(shinyAce)
library(YaleToolkit)
library(lubridate)

textStorage <- paste("### Code generated by intRo on", today(), "\n\n")

numericNames <- function(data) {
    return(subset(whatis(data), type == "numeric" & !(variable.name %in% c("year", "month", "day")))$variable.name)
}

shinyServer(function(input, output, session) {
    
    values <- reactiveValues(firstrun = TRUE)
    
    sourceDir <- function(path, ...) { for (nm in list.files(path, pattern = "\\.[Rr]$")) { source(file.path(path, nm), ...) } }
    
    sourceDir("modules")
    
    observe({
        if (input$vars == "onevar") updateSelectInput(session, "plottype", choices = c("Histogram" = "histogram", "Boxplot" = "boxplot1"), selected = "histogram")
    })
    
    observe({
        if (input$vars == "onevar") {
            updateSelectInput(session, "x", choices = numericNames(intro.data()), selected = numericNames(intro.data())[1])
            updateSelectInput(session, "y", choices = numericNames(intro.data()), selected = numericNames(intro.data())[2])
        }
        updateSelectInput(session, "group1", choices = numericNames(intro.data()), selected = numericNames(intro.data())[1])
        
        if (input$varts == "twovart") {
            updateSelectInput(session, "group2", choices = numericNames(intro.data()), selected = numericNames(intro.data())[2])
        }
    })
    
    observe({
        if (input$vars == "twovar") updateSelectInput(session, "plottype", choices = c("Scatterplot" = "scatterplot", "Line Chart" = "linechart", "Boxplot" = "boxplot2", "Bar Chart" = "barchart", "Pareto Chart" = "paretochart"), selected = "scatterplot")
    })
    
    observe({
        nms <- numericNames(intro.data())
        all.nms <- names(intro.data())
        new.x <- if (input$x %in% nms) input$x else nms[1]
        new.y <- if (input$y %in% nms) input$y else nms[2]
        
        if (input$vars == "twovar") {
            updateSelectInput(session, "y", choices = nms, selected = new.y)
            if (input$plottype %in% c("scatterplot", "linechart")) {
                updateSelectInput(session, "x", choices = nms, selected = new.x)
            } else if (input$plottype %in% c("boxplot2", "barchart", "paretochart")) {
                updateSelectInput(session, "x", choices = all.nms, selected = input$x)
            }
        }
    })
    
    observe({
        updateCheckboxGroupInput(session, "tblvars", choices=names(intro.data()))
    })
    
    observe({
        updateSelectInput(session, "xreg", choices = numericNames(intro.data()), selected = numericNames(intro.data())[1])
        updateSelectInput(session, "yreg", choices = numericNames(intro.data()), selected = numericNames(intro.data())[2])
    })
    
    intro.data <-reactive({
        data.initial <- data.module(input$data_own, input$data, input$own)
        
        if (values$firstrun) textStorage <<- paste(textStorage, "### ", input$`side-nav`,"\n", paste(c(readLines(paste("modules/", input$`side-nav`, ".R", sep = ""))), collapse = "\n"), "\n\n", sep = "")
        
        if (values$firstrun) updateAceEditor(session, "myEditor", value=textStorage)
                
        return(data.initial)
    })
    
    observe({
        if (input$`side-nav` != "Sources") values$firstrun <- FALSE
    })
    
    observe({
        if (!values$firstrun) {
            new.str <-  paste("### ", paste(input$`side-nav`, "\n", paste(readLines(paste("modules/", input$`side-nav`, ".R", sep = "")), collapse = "\n"), sep = ""), "\n\n", sep = "")
            
            ### Special case for plots
            if (input$`side-nav` == "Graphical") {
                new.str <- paste("### ", paste(input$`side-nav`, "\n", input$plottype, " <- ", paste(deparse(get(input$plottype)), collapse = "\n"), sep = ""), "\n\n", sep = "")
            }
            
            text.split <- strsplit(textStorage, "### ")[[1]]
            text.split <- text.split[-(text.split == "")]
            text.ind <- grep(input$`side-nav`, text.split)
            if (length(text.ind) == 0) text.ind <- length(text.split) + 1
            text.split[-text.ind] <- paste("###", text.split[-text.ind])
            text.split[text.ind] <- new.str
            
            textStorage <<- paste(text.split, collapse = "")
            
            updateAceEditor(session, "myEditor", value=textStorage)
        }
    })
    
    observe({
        ## Binwidth
        if (!is.null(input$x) & input$x != "") {
            rng <- range(intro.data()[,input$x])
            updateNumericInput(session, "binwidth", value=round((rng[2] - rng[1])/30, digits = 2))
        }
    })

    output$data <- renderDataTable({
        return(intro.data())
    }, options = list(iDisplayLength = 10))
    
    output$plot <- renderPlot({
        str.eval <- paste(input$plottype, "(intro.data(), input$x, input$y, input$bartype, input$binwidth)", sep = "")
        print(eval(parse(text = str.eval)))
    })
    
    output$summary <- renderTable({
        return(summarytable(intro.data(), input$tblvars))
    }, include.rownames = FALSE)
    
    output$regplot <- renderPlot({
        return(print(scatterplotreg(intro.data(), input$xreg, input$yreg)))
    })
    
    output$regtable <- renderTable({
        return(tablereg(intro.data(), input$xreg, input$yreg))
    })
    
    output$ttesttable <- renderText({
        return(ttesttable(intro.data(), input$group1, input$group2, input$varts == "twovart"))
    })
})
